### PR TITLE
Added install target to Makefile

### PR DESCRIPTION
**Pull request by jaylogue**

### CODE REVIEW

**Comment by jaylogue** [comment]
@jbglaw : Here's an install target for you.  If this looks good let me know and I will merge the change.

**Comment by jbglaw** [comment]
Works perfectly: http://toolchain.lug-owl.de/laminar/jobs/retrofuse/15

```
jbglaw@lili:~$ tar tzvf /var/cache/laminar/retrofuse-dd0656fa62c6a4bbe1c82d60612e5a27229be128.tar.gz
drwxr-xr-x foo/foo           0 2023-08-21 08:23 _inst_/
drwxr-xr-x foo/foo           0 2023-08-21 08:23 _inst_/bin/
drwxr-xr-x foo/foo           0 2023-08-21 08:23 _inst_/bin/bin/
-rwxr-xr-x foo/foo       64248 2023-08-21 08:20 _inst_/bin/bin/v7fs
-rwxr-xr-x foo/foo       68424 2023-08-21 08:20 _inst_/bin/bin/bsd29fs
-rwxr-xr-x foo/foo       88944 2023-08-21 08:20 _inst_/bin/bin/bsd211fs
-rwxr-xr-x foo/foo       60152 2023-08-21 08:20 _inst_/bin/bin/v6fs
```

**Comment by jaylogue** [comment]
Great!  Thanks for testing this.

BTW, was the double "bin" directories intentional?  (\_inst\_/**bin/bin**/...)

**Comment by jbglaw** [comment]
Good catch! ...but actually, the answer is kind-of "Yes!" My invocation (see the logging helper `log_execute` call right above the referenced build log) had `prefix=/bin` instead of `prefix=/usr` set, so it was a typo on my side and subsequently correctly handled within the new `Makefile` target.

**Comment by jbglaw** [comment]
New CI build (now from `master` instead of the `feature/install` branch) here: http://toolchain.lug-owl.de/laminar/jobs/retrofuse/17

Thanks!

**Pull request merged**
